export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/auth/login/',
    REFRESH_TOKEN: '/api/v1/auth/token/refresh/',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password/',
    FORGOT_PASSWORD_VERIFY_OTP: '/api/v1/auth/forgot-password/verify-otp/',
    FORGOT_PASSWORD_RESEND_OTP: '/api/v1/auth/forgot-password/resend-otp/',
    RESET_PASSWORD: '/api/v1/auth/forgot-password/reset-password/',
    LOGOUT: '/api/v1/auth/logout/',
  },
  DRIVER: {
    ACTIVATE_ACCOUNT: '/api/v1/drivers/activate-account/',
    ACTIVATE_ACCOUNT_VERIFY_OTP: '/api/v1/drivers/activate-account/verify-otp/',
    ACTIVATE_ACCOUNT_RESEND_OTP: '/api/v1/drivers/activate-account/resend-otp/',
    STATUS: '/api/v1/drivers/me/status/',
  },
  USERS: {
    ME: '/api/v1/users/me/',
    CHANGE_PHONE_REQUEST: '/api/v1/users/me/change-phone/',
    CHANGE_PHONE_RESEND: '/api/v1/users/me/change-phone/resend-otp/',
    CHANGE_PHONE_VERIFY: '/api/v1/users/me/change-phone/verify-otp/',
    CHANGE_PASSWORD: '/api/v1/users/me/change-password/',
  },
  TRIPS: {
    HISTORY: '/trips/history/',
    CURRENT: '/trips/current/',
    BY_ID: (tripId: number) => `/trips/${tripId}/`,
    LOCATION: (tripId: number) => `/trips/${tripId}/location/`,
    STATUS_CHOICES: '/trips/status-choices/',
    ROUTE: (tripId: number) => `/trips/trips/${tripId}/route/`,
    ACCEPT: (tripId: number) => `/trips/${tripId}/accept/`,
    CANCEL: (tripId: number) => `/trips/trips/${tripId}/cancel/`,
    COMPLETE: (tripId: number) => `/trips/${tripId}/complete/`,
    I_AM_HERE: (tripId: number) => `/trips/${tripId}/i-am-here/`,
    RESEND_PIN: (tripId: number) => `/trips/${tripId}/resend-pin/`,
    VERIFY_PIN: (tripId: number) => `/trips/${tripId}/verify-pin/`,
  },
  NOTIFICATIONS: {
    LIST: '/api/v1/notifications/',
    TYPES: '/api/v1/notifications/types/',
    DEVICE_TOKENS: '/api/v1/notifications/device-tokens/',
    DEACTIVATE: (id: number) =>
      `/api/v1/notifications/device-tokens/${id}/deactivate/`,
    MARK_READ: (id: number) => `/api/v1/notifications/${id}/read/`,
    DELETE: (id: number) => `/api/v1/notifications/${id}/`,
  },
} as const;
